export const gitmojis = [
  {
    emoji: '🚀',
    entity: '&#x1f680;',
    code: ':rocket:',
    description: 'New feature or proposition',
    type: 'feat',
    name: 'rocket',
    semver: null,
  },
  {
    emoji: '🐛',
    entity: '&#x1f41b;',
    code: ':bug:',
    description: 'Fix a bug',
    type: 'fix',
    name: 'bug',
    semver: 'patch',
  },
  {
    emoji: '📝',
    entity: '&#x1f4dd;',
    code: ':memo:',
    description: 'Add or update documentation',
    type: 'docs',
    name: 'docs',
    semver: null,
  },
  {
    emoji: '💄',
    entity: '&#ff99cc;',
    code: ':lipstick:',
    description: 'Add or update the UI and style files.',
    type: 'style',
    name: 'lipstick',
    semver: 'patch',
  },
  {
    emoji: '♻️',
    entity: '&#x267b;',
    code: ':recycle:',
    description: 'Refactor code.',
    type: 'refactor',
    name: 'recycle',
    semver: null,
  },
  {
    emoji: '🧪',
    entity: '&#x1F9EA;',
    code: ':test_tube:',
    description: 'Add test cases, test files or fix existing tests.',
    type: 'test',
    name: 'test-tube',
    semver: null,
  },
  {
    emoji: '🔖',
    entity: '&#x1f516;',
    code: ':bookmark:',
    description: 'Release / Version tags.',
    type: 'release',
    name: 'bookmark',
    semver: null,
  },
  {
    emoji: '🚧',
    entity: '&#x1f6a7;',
    code: ':construction:',
    description: 'Work in progress.',
    type: 'wip',
    name: 'construction',
    semver: null,
  },
  {
    emoji: '📦',
    entity: '&#1f4e6;',
    code: ':package:',
    description: 'Update compiled files or packages.',
    type: 'chore',
    name: 'package',
    semver: null,
  },
];
