name: CI

on:
  push:
    branches:
      - v2

permissions:
  contents: write
  pull-requests: write

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "npm"
      - name: Install dependencies and build
        run: |
            export CLIENT_URL=${{ secrets.CLIENT_URL }}
            export API_KEY=${{ secrets.API_KEY }}
            npm install --frozen-lockfile
            npm run build --if-present
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
